- name: get lxcalog data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: lxcalog
  register: rslt
  tags:
     lxcalog

