- name: get powersupplies data from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    command_options: powersupplies
  register: rslt
  tags:
     powersupplies
